spring.datasource.url=jdbc:postgresql://localhost:5433/starter
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.platform=postgres

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml